### ISSUE TITLE
Error when opening configuration panel

### ISSUE THREAD

**Issue by mikattack** [Phanx/PhanxBuffs#6] opened 2016-07-27 02:17 UTC
From BugSack:
    2x PhanxBuffs\Options-Options.lua:246: attempt to index global 'db' (a nil value)
    PhanxBuffs\Options-Options.lua:246: in function `refresh'
    ...hanxConfig-OptionsPanel\PhanxConfig-OptionsPanel-20150112.lua:45: in function <...hanxConfig-OptionsPanel\PhanxConfig-OptionsPanel.lua:37>
    [C]: in function`Show'
    FrameXML\InterfaceOptionsFrame.lua:28: in function `InterfaceOptionsList_DisplayPanel'
    FrameXML\InterfaceOptionsFrame.lua:46: in function`InterfaceOptionsListButton_OnClick'
    [string "_:OnClick"]:2: in function <[string "_:OnClick"]:1>

(doesn't seem to paste well)

**Comment by Phanx** [comment] 2016-07-28 11:50
Duplicate of #4

**Closed as completed by Phanx** 2016-07-28 11:50 UTC
